apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: google-ads-mcp
  labels:
    app: google-ads-mcp
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: google-ads-mcp
  type: ClusterIP